# Generated by Django 2.2.19 on 2022-03-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('start_date', models.DateTimeField(verbose_name='Время старта')),
                ('finish_date', models.DateTimeField(verbose_name='Время завершения')),
            ],
        ),
    ]
