# Generated by Django 2.2.19 on 2022-03-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_customer_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-id']},
        ),
    ]
