# Generated by Django 2.2.19 on 2022-03-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_auto_20220318_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mailing',
        ),
        migrations.AddField(
            model_name='message',
            name='mailing',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages', to='mailing.Mailing', verbose_name='Рассылка'),
        ),
    ]
