# Generated by Django 2.2.19 on 2022-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_auto_20220318_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages', to='mailing.Message', verbose_name='Рассылка'),
        ),
    ]
