# Generated by Django 2.2.19 on 2022-03-18 20:45

from django.db import migrations, models
import mailing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_auto_20220318_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[mailing.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='mailings', to='mailing.Message', verbose_name='Сщщбщения'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
